"""empty message

Revision ID: 13fa5c65efaf
Revises: c92e2e80f3cf
Create Date: 2020-06-02 22:10:18.159689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fa5c65efaf'
down_revision = 'c92e2e80f3cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('website', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
